        !COMPILER-GENERATED INTERFACE MODULE: Fri May 24 12:14:56 2019
        MODULE COMPPROJECTIONINT__genmod
          INTERFACE 
            SUBROUTINE COMPPROJECTIONINT(A,B,ID,P)
              INTEGER(KIND=4) :: A
              INTEGER(KIND=4) :: B
              INTEGER(KIND=4) :: ID
              REAL(KIND=8) :: P(10)
            END SUBROUTINE COMPPROJECTIONINT
          END INTERFACE 
        END MODULE COMPPROJECTIONINT__genmod
