        !COMPILER-GENERATED INTERFACE MODULE: Fri May 24 12:14:56 2019
        MODULE COMPVOLUMEINT__genmod
          INTERFACE 
            SUBROUTINE COMPVOLUMEINT
              USE GLOBAL
            END SUBROUTINE COMPVOLUMEINT
          END INTERFACE 
        END MODULE COMPVOLUMEINT__genmod
