        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 11 21:08:17 2018
        MODULE COMPVOLUMEINT__genmod
          INTERFACE 
            SUBROUTINE COMPVOLUMEINT
              USE GLOBAL
            END SUBROUTINE COMPVOLUMEINT
          END INTERFACE 
        END MODULE COMPVOLUMEINT__genmod
