        !COMPILER-GENERATED INTERFACE MODULE: Fri May 24 12:14:57 2019
        MODULE COTRANS__genmod
          INTERFACE 
            SUBROUTINE COTRANS
            END SUBROUTINE COTRANS
          END INTERFACE 
        END MODULE COTRANS__genmod
