        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 11 21:08:18 2018
        MODULE COTRANS__genmod
          INTERFACE 
            SUBROUTINE COTRANS
            END SUBROUTINE COTRANS
          END INTERFACE 
        END MODULE COTRANS__genmod
