        !COMPILER-GENERATED INTERFACE MODULE: Fri May 24 12:14:57 2019
        MODULE PREVARSOUT__genmod
          INTERFACE 
            SUBROUTINE PREVARSOUT
            END SUBROUTINE PREVARSOUT
          END INTERFACE 
        END MODULE PREVARSOUT__genmod
