        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 11 21:08:18 2018
        MODULE PREVARSOUT__genmod
          INTERFACE 
            SUBROUTINE PREVARSOUT
            END SUBROUTINE PREVARSOUT
          END INTERFACE 
        END MODULE PREVARSOUT__genmod
