        !COMPILER-GENERATED INTERFACE MODULE: Fri May 24 12:14:56 2019
        MODULE VARSOUT__genmod
          INTERFACE 
            SUBROUTINE VARSOUT
            END SUBROUTINE VARSOUT
          END INTERFACE 
        END MODULE VARSOUT__genmod
