        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 11 21:08:17 2018
        MODULE VARSOUT__genmod
          INTERFACE 
            SUBROUTINE VARSOUT
            END SUBROUTINE VARSOUT
          END INTERFACE 
        END MODULE VARSOUT__genmod
