        !COMPILER-GENERATED INTERFACE MODULE: Fri May 24 12:14:57 2019
        MODULE VFDATAOUT__genmod
          INTERFACE 
            SUBROUTINE VFDATAOUT
            END SUBROUTINE VFDATAOUT
          END INTERFACE 
        END MODULE VFDATAOUT__genmod
