        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 11 21:08:18 2018
        MODULE VFDATAOUT__genmod
          INTERFACE 
            SUBROUTINE VFDATAOUT
            END SUBROUTINE VFDATAOUT
          END INTERFACE 
        END MODULE VFDATAOUT__genmod
